FROM postgres:latest
#RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
RUN mkdir -p /var/lib/postgresql/data
RUN chown -R postgres:postgres /var/lib/postgresql
RUN chown -R postgres:postgres /var/lib/postgresql/data

